### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by BarbzYHOOL** [larsks/ansible-role#20]
I have this task:
```

- name: Symlink "smartless" in "/usr/local/bin/"
  file:
    state: link
    src: "{{ smartless_clone_dir_path }}/smartless/smartless"
    dest: "/usr/local/bin/smartless"
    owner: "{{ smartless_user_name | default(omit) }}"
    group: "{{ smartless_user_name | default(omit) }}"
    mode: "u+rwx,g+rwx,o+rx-w"
```

And this error using `ansible-role`:
`
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error while linking: [Errno 13] Permission denied", "path": "/usr/local/bin/smartless", "state": "absent"}
`

I managed to get past the error but I don't know how, I tried -K, -b, -u but it didn't work then suddenly it worked

Can someone explain me? (it's been a while I used ansible tho)

Also this tool is really useful
